### ISSUE TITLE
数据监控方案

### ISSUE THREAD

**Issue by sorrycc** [ant-tool/atool-monitor#1]
## 整体方案

为了规避安全风险，服务器部署在内网，然后通过判断 ip，只收集 ali 内网用户的数据。
## 收集字段
- `package.json`
- `type`: crash | execCommand | manully
- `command`: 通过 process.argv 获得
- `os/node/npm/tnpm` 版本
- `message`：crash 信息等
### 服务端

mongodb 数据库
- [x] 申请内网机器和域名， @jaredleechn 
- [x] 实现接口 `POST /monitor?version=0.1.0 --data {JSON}`
- [ ] 页面展现、查询及相关接口，先实现 `build 工具及版本分布` 和 `antd 版本分布`
### 客户端

接口设计如下：

``` javascript
// Normal usage
require('atool-monitor').bind(program);
// 自定义数据
require('atool-monitor').bind(program, data => {
  // ... 添加或修改字段
  return data;
});
// 手动发送数据
require('atool-monitor').emit(data);
```
- [x] `atool-monitor`，命令执行、应用程序 crash 时判断是否
- [x] `is-ali-env`，通过 ip 或其他方式判断是否 ali 环境
### 布点

依赖 `atool-monitor` 的 mirror 版本，便于升级。

> 先布点 `atool-build`，没啥问题的话就全量铺开。
- [x] atool-build
  - [x] 0.6.x
  - [x] 0.4.x, 0.5.x
- [x] dora
- [x] antd-bin
- [x] spm-webpack
### 其他
- [ ] [atool-build 改造成 cluster 的方式，支持 crash 日志收集](https://github.com/ant-tool/atool-build/issues/128)
- [ ] dora 收集出错日志

**Comment by sorrycc** [comment]
https://github.com/ant-tool/is-ali-env

**Comment by sorrycc** [comment]
实现过程中发现非持续执行的命令(比如 atool-build) crash 收集方案需要改造现有工具为 cluster，有侵入性，暂不处理。

改为收集 `dora` 出错信息。

**Comment by sorrycc** [comment]
atool-build@0.6.x 已经部署数据监控脚本，先观察一段时间。

**Comment by sorrycc** [comment]
## 如何布点

先在 `package.json` 中添加 `atool-monitor`，版本为 `0.x` 。

``` diff
"dependencies": {
+  "atool-monitor": "0.x",
}
```

然后在相关的 bin 文件中添加：

``` diff
+ require('atool-monitor').emit();
```

例子：
https://github.com/ant-tool/atool-build/pull/127

**Comment by sorrycc** [comment]
dora 和 antd-bin 布点完成。

**Comment by soda-x** [comment]
spm-webpack 布点完成
- [x] 0.6.x 
- [x] 0.7.x 
- [x] 0.8.x 
- [x] 1.0.x

**Comment by sunny920406** [comment]
在roadhog@2.2.0中运行命令有检查是不是内部环境，如果不是就会把接口返回码打印在控制台，比如404，看着很难受啊:-(
